IPT/IPT/Models/Restaurent.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Country { get; set; }
        public string ManagerName { get; set; }
    }
}

IPT/IPT/Controllers/RestaurentController.cs
using IPT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IPT.Controllers
{
    public class RestaurentController : Controller
    {
        // GET: Restaurent
        public ActionResult RestaurentList1()
        {

            using (FoodManagementEntities7 fd = new FoodManagementEntities7())
            {
                return View(fd.Restaurents.ToList());

            }

         }
        public ActionResult BranchList(int id)
        {

            using (FoodManagementEntities10 fd = new FoodManagementEntities10())
            {
                return View( );

            }
        
         }
    }
}

IPT/IPT/Views/Restaurent/RestaurentList.cshtml
@{
    ViewBag.Title = "RestaurentList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Restaurent List</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                            <thead>

                                <tr role="row">
                                    <th rowspan="1" colspan="1">ID</th>
                                    <th rowspan="1" colspan="1">Name</th>
                                    <th rowspan="1" colspan="1">Phone Number</th>
                                    <th rowspan="1" colspan="1">Address</th>
                                    <th rowspan="1" colspan="1">Country </th>
                                    <th rowspan="1" colspan="1">Manager</th>
                                    <th rowspan="1" colspan="1">Branches</th>
                                </tr>


                            </thead>
                            <tfoot>
                                <tr role="row">
                                    <th rowspan="1" colspan="1">ID</th>
                                    <th rowspan="1" colspan="1">Name</th>
                                    <th rowspan="1" colspan="1">Phone Number</th>
                                    <th rowspan="1" colspan="1">Address</th>
                                    <th rowspan="1" colspan="1">Country </th>
                                    <th rowspan="1" colspan="1">Manager</th>
                                    <th rowspan="1" colspan="1">Branches</th>
                                </tr>

                            </tfoot>
                            <tbody>
                                @foreach (var aa in Model)
                                {
                                <tr role="row" class="odd">
                                    <td>@aa.Id</td>
                                    <td>@aa.Name </td>
                                    <td>@aa.Phone</td>
                                    <td>@aa.Address</td>
                                    <td>@aa.Country</td>
                                    <td>@aa.Manager</td>
                                    <td>
                                        <a href='@Url.Action( "BranchList1","Restaurent" , new { id = aa.Id })'  class="btn btn-info btn-icon-split">
                                            <span class="icon text-white-50">
                                                <i class="fas fa-info-circle"></i>
                                            </span>
                                            <span class="text">Branches</span>
                                        </a>
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

IPT/IPT/Views/Restaurent/RestaurentList1.cshtml
@model IEnumerable<IPT.Models.Restaurent>

@{
    ViewBag.Title = "RestaurentList1";
}


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Order List</h6>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                <div class="row">

                    <div class="col-sm-12">


                        <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Id)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Phone)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Country)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ManagerName)
                                </th>
                                <th>Branches </th>
                            </tr>
                            @{
                                int i = 0;

                                foreach (var item in Model)
                                {
                                    i = i + 1;
                            <tr>
                                <td>
                                    @i
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                 <td>
                                    @Html.DisplayFor(modelItem => item.Phone)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Country)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ManagerName)
                                </td>
                                <td>
                                    <a href='@Url.Action( "BranchList","Restaurent" , new {id = item.Id  })' class="btn btn-info btn-icon-split">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-info-circle"></i>
                                        </span>
                                        <span class="text">Branches</span>
                                    </a>
                                </td>
                             </tr>
                                }
                            }

                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>