IPT/IPT/Controllers/IndexController.cs
using IPT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IPT.Controllers
{
    public class IndexController : Controller
    {
        // GET: Index
        public ActionResult Index()
        {
            IndexModel model = new IndexModel();
            model.id = 123;
            model.name = "Saqlain";

            return View(model);
        }


    }
}

IPT/IPT/Controllers/MenuController.cs
using IPT.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IPT.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
        public ActionResult GetFoodItem1()
        {
                 using(FoodManagementEntities3  fd = new FoodManagementEntities3())
            {
                return View(fd.FoodItems.ToList());

            }

        }
        public ActionResult AddFoodItem1()
        {
            return View("AddFoodItem1");
        }

        [HttpPost]
        public ActionResult AddFoodItem1(FoodItem item)
        {
            using (FoodManagementEntities3 fd = new FoodManagementEntities3())
            {

                fd.FoodItems.Add(item);
                fd.SaveChanges();
            }
            return RedirectToAction("GetFoodItem1");
        }

        public ActionResult Edit(int id)
        {
            using (FoodManagementEntities3 fd = new FoodManagementEntities3())
            {
                return View(fd.FoodItems.Where(x => x.Id == id).FirstOrDefault() );
            }
         }
        [HttpPost]
        public ActionResult Edit(int id, FoodItem item)
        {
            using (FoodManagementEntities3 fd = new FoodManagementEntities3())
            {
                fd.Entry(item).State = EntityState.Modified;
                fd.SaveChanges();
             }
            return RedirectToAction("GetFoodItem1");   
        }

        public ActionResult Delete(int id)
        {
            using (FoodManagementEntities3 fd = new FoodManagementEntities3())
            {
                FoodItem i = fd.FoodItems.Where(x => x.Id == id).FirstOrDefault();
                fd.FoodItems.Remove(i);
                fd.SaveChanges();
            }
            return RedirectToAction("GetFoodItem1");
        }

        public ActionResult OrderList1()
        {

            using (FoodManagementEntities4 fd = new FoodManagementEntities4())
            {
                return View(fd.Orders.ToList());

            }



        }

        public ActionResult PaymentList1()
        {

            using (FoodManagementEntities6 fd = new FoodManagementEntities6())
            {
                return View(fd.Payment1.ToList());

            }
             
        }
        public ActionResult AddFood()
        {


            return View();
        }

    }
}

IPT/IPT/Views/Menu/AddFoodItem.cshtml
@{
    ViewBag.Title = "AddFoodItem";
}
<form class="border border-light p-4" action="Menu/AddFood">

    <p class="h3 mb-4">Add Food Item</p>

    <!-- Name -->
    <label for="text">Name:</label>
    <input type="text" id="defaultContactFormName" class="form-control mb-4" placeholder="Name">

    <!-- Email -->
    <label for="Price">Price:</label>
    <input type="number" id="Price" class="form-control mb-4" placeholder="Price">

    <label for="Quantity">Quantity In Stock:</label>
    <input type="number" id="Quantity" class="form-control mb-4" placeholder="Quantity">

    <!-- Message -->
    <!-- Send button -->
    <button class="btn btn-info btn-block" type="submit">Send</button>

</form>

IPT/IPT/Views/Menu/AddFoodItem1.cshtml
@model IPT.Models.FoodItem

@{
    ViewBag.Title = "AddFoodItem1";
}
 
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal border border-light p-4">
        <h4>Add FoodItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info btn-block" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

IPT/IPT/Views/Menu/Edit.cshtml
@model IPT.Models.FoodItem

@{
    ViewBag.Title = "Edit";
}
 
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal border border-light p-4">
            <h4>Edit FoodItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info btn-block" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GetFoodItem1")
</div>

IPT/IPT/Views/Menu/GetFoodItem1.cshtml
@model IEnumerable<IPT.Models.FoodItem>

@{
    ViewBag.Title = "GetFoodItem1";
}


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Food Items</h6>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                <div class="row">

                    <div class="col-sm-12">

                        <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">

                            <thead>

                                <tr role="row">
                                    <th rowspan="1" colspan="1">
                                        @Html.DisplayNameFor(model => model.Id)
                                    </th>
                                    <th rowspan="1" colspan="1">
                                        @Html.DisplayNameFor(model => model.Name)
                                    </th>
                                    <th rowspan="1" colspan="1">
                                        @Html.DisplayNameFor(model => model.Price)
                                    </th>
                                    <th rowspan="1" colspan="1">
                                        @Html.DisplayNameFor(model => model.Quantity)
                                    </th>
                                    <th rowspan="1" colspan="1">
                                        Actions
                                    </th>
                                </tr>

                            </thead>

                            <tfoot>

                                <tr role="row">
                                    <th rowspan="1" colspan="1">
                                        @Html.DisplayNameFor(model => model.Id)
                                    </th>
                                    <th rowspan="1" colspan="1">
                                        @Html.DisplayNameFor(model => model.Name)
                                    </th>
                                    <th rowspan="1" colspan="1">
                                        @Html.DisplayNameFor(model => model.Price)
                                    </th>
                                    <th rowspan="1" colspan="1">
                                        @Html.DisplayNameFor(model => model.Quantity)
                                    </th>
                                    <th rowspan="1" colspan="1">
                                        Actions
                                    </th>
                                </tr>

                            </tfoot>
                            @{
                                int i = 1;

                                foreach (var item in Model)
                                {

                                    <tr role="row">
                                        <td>
                                            @i
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Price)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Quantity)
                                        </td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                        </td>
                                    </tr>
                                    i = i + 1;
                                }
                            }
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

IPT/IPT/Views/Menu/OrderList.cshtml
@{
    ViewBag.Title = "OrderList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Order List</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                <div class="row">




                    <div class="col-sm-12">
                        <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                            <thead>

                                <tr role="row">
                                    <th rowspan="1" colspan="1">Customer ID</th>
                                    <th rowspan="1" colspan="1">Order NO</th>
                                    <th rowspan="1" colspan="1">Order Date</th>
                                    <th rowspan="1" colspan="1">Status</th>
                                    <th rowspan="1" colspan="1">Location </th>
                                    <th rowspan="1" colspan="1">Food Id</th>
                                    <th rowspan="1" colspan="1">Quantity</th>
                                </tr>

                            </thead>
                            <tfoot>
                                <tr role="row">
                                    <th rowspan="1" colspan="1">Customer ID</th>
                                    <th rowspan="1" colspan="1">Order NO</th>
                                    <th rowspan="1" colspan="1">Order Date</th>
                                    <th rowspan="1" colspan="1">Status</th>
                                    <th rowspan="1" colspan="1">Location </th>
                                    <th rowspan="1" colspan="1">Food Id</th>
                                    <th rowspan="1" colspan="1">Quantity</th>
                                </tr>

                            </tfoot>
                            <tbody>
                                <tr role="row" class="odd">
                                    <td>1</td>
                                    <td>101 </td>
                                    <td>2-8-2019</td>
                                    <td>Complete</td>
                                    <td>Gulshan-e-Iqbal</td>
                                    <td>110</td>
                                    <td>1</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>1</td>
                                    <td>101 </td>
                                    <td>2-8-2019</td>
                                    <td>Complete</td>
                                    <td>Gulshan-e-Iqbal</td>
                                    <td>110</td>
                                    <td>1</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>1</td>
                                    <td>101 </td>
                                    <td>2-8-2019</td>
                                    <td>Complete</td>
                                    <td>Gulshan-e-Iqbal</td>
                                    <td>110</td>
                                    <td>1</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>1</td>
                                    <td>101 </td>
                                    <td>2-8-2019</td>
                                    <td>Complete</td>
                                    <td>Gulshan-e-Iqbal</td>
                                    <td>110</td>
                                    <td>1</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>1</td>
                                    <td>101 </td>
                                    <td>2-8-2019</td>
                                    <td>Complete</td>
                                    <td>Gulshan-e-Iqbal</td>
                                    <td>110</td>
                                    <td>1</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>1</td>
                                    <td>101 </td>
                                    <td>2-8-2019</td>
                                    <td>Complete</td>
                                    <td>Gulshan-e-Iqbal</td>
                                    <td>110</td>
                                    <td>1</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>1</td>
                                    <td>101 </td>
                                    <td>2-8-2019</td>
                                    <td>Complete</td>
                                    <td>Gulshan-e-Iqbal</td>
                                    <td>110</td>
                                    <td>1</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>1</td>
                                    <td>101 </td>
                                    <td>2-8-2019</td>
                                    <td>Complete</td>
                                    <td>Gulshan-e-Iqbal</td>
                                    <td>110</td>
                                    <td>1</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>1</td>
                                    <td>101 </td>
                                    <td>2-8-2019</td>
                                    <td>Complete</td>
                                    <td>Gulshan-e-Iqbal</td>
                                    <td>110</td>
                                    <td>1</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>1</td>
                                    <td>101 </td>
                                    <td>2-8-2019</td>
                                    <td>Complete</td>
                                    <td>Gulshan-e-Iqbal</td>
                                    <td>110</td>
                                    <td>1</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

IPT/IPT/Views/Menu/OrderList1.cshtml
@model IEnumerable<IPT.Models.Order>

@{
    ViewBag.Title = "OrderList1";
}
 

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Order List</h6>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                <div class="row">

                    <div class="col-sm-12">


                        <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">

                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Id)

                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.CId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.OrderDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.OrderNo)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Status)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Location)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.FoodId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Quantity)
                                </th> 
                            </tr>
                            @{
                                int i = 0;
                                foreach (var item in Model)
                                {
                                    i = i + 1;
                                    <tr>
                                        <td>
                                            @i
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CId)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.OrderDate)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.OrderNo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Status)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Location)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FoodId)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Quantity)
                                        </td>
                                    </tr>
                                }

                            }
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

IPT/IPT/Views/Menu/PaymentList.cshtml
@{
    ViewBag.Title = "PaymentList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Payment List</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                <div class="row">




                    <div class="col-sm-12">
                        <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                            <thead>

                                <tr role="row">
                                    <th rowspan="1" colspan="1">Check Num</th>
                                    <th rowspan="1" colspan="1">Customer ID</th>
                                    <th rowspan="1" colspan="1">Payment Date</th>
                                    <th rowspan="1" colspan="1">Amount</th>
                                    <th rowspan="1" colspan="1">Order ID </th>
                                </tr>

                            </thead>
                            <tfoot>
                                <tr role="row">
                                    <th rowspan="1" colspan="1">Check Num</th>
                                    <th rowspan="1" colspan="1">Customer ID</th>
                                    <th rowspan="1" colspan="1">Payment Date</th>
                                    <th rowspan="1" colspan="1">Amount</th>
                                    <th rowspan="1" colspan="1">Order ID </th>
                                </tr>


                            </tfoot>
                            <tbody>
                                <tr role="row" class="odd">
                                    <td>10120111-232320112</td>
                                    <td>1 </td>
                                    <td>2-8-2019</td>
                                    <td>800</td>
                                    <td>101</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>10120111-232320112</td>
                                    <td>1 </td>
                                    <td>2-8-2019</td>
                                    <td>800</td>
                                    <td>101</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>10120111-232320112</td>
                                    <td>1 </td>
                                    <td>2-8-2019</td>
                                    <td>800</td>
                                    <td>101</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>10120111-232320112</td>
                                    <td>1 </td>
                                    <td>2-8-2019</td>
                                    <td>800</td>
                                    <td>101</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>10120111-232320112</td>
                                    <td>1 </td>
                                    <td>2-8-2019</td>
                                    <td>800</td>
                                    <td>101</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>10120111-232320112</td>
                                    <td>1 </td>
                                    <td>2-8-2019</td>
                                    <td>800</td>
                                    <td>101</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>10120111-232320112</td>
                                    <td>1 </td>
                                    <td>2-8-2019</td>
                                    <td>800</td>
                                    <td>101</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>10120111-232320112</td>
                                    <td>1 </td>
                                    <td>2-8-2019</td>
                                    <td>800</td>
                                    <td>101</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <td>10120111-232320112</td>
                                    <td>1 </td>
                                    <td>2-8-2019</td>
                                    <td>800</td>
                                    <td>101</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

IPT/IPT/Views/Menu/PaymentList1.cshtml
@model IEnumerable<IPT.Models.Payment1>

@{
    ViewBag.Title = "PaymentList1";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Order List</h6>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                <div class="row">

                    <div class="col-sm-12">


                        <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Id)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PaymentDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Amount)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.OrderID)
                                </th>
                            </tr>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PaymentDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Amount)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.OrderID)
                                    </td>
                                 </tr>
                            }

                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>